"""Unit tests for source_id_priority module (TH-422).

The mirobody.pulse package __init__ chain pulls heavy external deps
(webauthn, etc) that aren't needed for this pure-string module. To keep
the test runnable in isolation, load source_id_priority.py directly via
importlib and run via unittest's standalone main.

Run with:
    python3 mirobody/pulse/core/aggregate_indicator/aggregators/test_source_id_priority.py
"""

import importlib.util
import os
import sqlite3
import unittest
from typing import Optional
from unittest import mock

_MOD_PATH = os.path.join(os.path.dirname(__file__), "source_id_priority.py")
_spec = importlib.util.spec_from_file_location("source_id_priority", _MOD_PATH)
source_id_priority = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(source_id_priority)

APPLE_SOURCES = source_id_priority.APPLE_SOURCES
APPLE_SOURCE_ID_PRIORITY_RULES = source_id_priority.APPLE_SOURCE_ID_PRIORITY_RULES
DEFAULT_PRIORITY = source_id_priority.DEFAULT_PRIORITY
build_apple_priority_case = source_id_priority.build_apple_priority_case


def _eval_case_in_sqlite(case_expr: str, source: str, source_id: Optional[str]) -> int:
    """Evaluate the generated CASE expression against sqlite to get an
    actual integer priority. sqlite is SQL-92 compatible for CASE/LIKE so
    the result matches what PostgreSQL would produce.
    """
    conn = sqlite3.connect(":memory:")
    try:
        cur = conn.cursor()
        cur.execute("CREATE TABLE t (source TEXT, source_id TEXT)")
        cur.execute("INSERT INTO t VALUES (?, ?)", (source, source_id))
        cur.execute(f"SELECT {case_expr} FROM t")
        return cur.fetchone()[0]
    finally:
        conn.close()


class TestBuildAppleCaseExpression(unittest.TestCase):
    """Tests for the SQL CASE expression string generated by build_apple_priority_case."""

    def test_returns_well_formed_case_expression(self):
        expr = build_apple_priority_case("source", "source_id")
        self.assertIsInstance(expr, str)
        self.assertTrue(expr.startswith("CASE"))
        self.assertTrue(expr.endswith("END"))

    def test_contains_all_apple_sources(self):
        expr = build_apple_priority_case("source", "source_id")
        for src in APPLE_SOURCES:
            self.assertIn(f"'{src}'", expr)

    def test_contains_all_priority_rules(self):
        expr = build_apple_priority_case("source", "source_id")
        for pattern, priority, _mode in APPLE_SOURCE_ID_PRIORITY_RULES:
            self.assertIn(pattern, expr)
            self.assertIn(f"THEN {priority}", expr)

    def test_contains_default_priority_branch(self):
        expr = build_apple_priority_case("source", "source_id")
        self.assertIn(f"ELSE {DEFAULT_PRIORITY}", expr)

    def test_uses_provided_column_names(self):
        expr = build_apple_priority_case("s.source", "s.source_id")
        self.assertIn("s.source", expr)
        self.assertIn("s.source_id", expr)
        # Unqualified names should not leak in as column refs.
        self.assertNotIn(" source NOT IN", expr)
        self.assertNotIn(" source_id LIKE", expr)

    def test_rejects_unknown_match_mode(self):
        with mock.patch.object(
            source_id_priority,
            "APPLE_SOURCE_ID_PRIORITY_RULES",
            [("com.bad.app", 50, "regex")],  # not a supported mode
        ):
            with self.assertRaises(ValueError):
                source_id_priority.build_apple_priority_case("source", "source_id")


class TestEvaluatedPriority(unittest.TestCase):
    """Evaluate the CASE expression against sqlite to verify runtime semantics."""

    def setUp(self):
        self.case_expr = build_apple_priority_case("source", "source_id")

    def test_non_apple_source_returns_zero(self):
        # Non-apple sources always get priority 0 -> no filtering happens for them.
        self.assertEqual(_eval_case_in_sqlite(self.case_expr, "theta.theta_oura", None), 0)
        self.assertEqual(_eval_case_in_sqlite(self.case_expr, "theta.theta_oura", "irrelevant"), 0)
        self.assertEqual(_eval_case_in_sqlite(self.case_expr, "vital.oura", "com.ouraring.oura"), 0)
        self.assertEqual(_eval_case_in_sqlite(self.case_expr, "vital.dexcom_v3", None), 0)

    def test_apple_watch_uuid_matches_prefix(self):
        self.assertEqual(
            _eval_case_in_sqlite(
                self.case_expr,
                "apple_health",
                "com.apple.health.FB876F40-9196-4EEC-99BC-25F0F819C13D",
            ),
            10,
        )
        self.assertEqual(
            _eval_case_in_sqlite(
                self.case_expr,
                "apple_health_watch",
                "com.apple.health.A93FCC37-03E0-4270-8F1B-5937B695A561",
            ),
            10,
        )
        # mobiletimer must NOT be swallowed by the com.apple. prefix.
        self.assertEqual(
            _eval_case_in_sqlite(self.case_expr, "apple_health", "com.apple.mobiletimer"),
            99,
        )

    def test_known_third_party_apps_get_exact_priority(self):
        cases = {
            "com.ouraring.oura":     50,
            "com.whoop.iphone":      60,
            "com.neybox.Pillow":     70,
            "com.aliphcom.upopen":   80,
            "com.apple.mobiletimer": 99,
        }
        for sid, expected in cases.items():
            with self.subTest(source_id=sid):
                self.assertEqual(
                    _eval_case_in_sqlite(self.case_expr, "apple_health", sid),
                    expected,
                )

    def test_unknown_source_id_falls_back_to_default(self):
        for sid in ["com.unknown.newapp", "unknown", ""]:
            with self.subTest(source_id=sid):
                self.assertEqual(
                    _eval_case_in_sqlite(self.case_expr, "apple_health", sid),
                    DEFAULT_PRIORITY,
                )

    def test_null_source_id_falls_back_to_default(self):
        # NULL source_id: all LIKE / = comparisons evaluate to NULL (unknown),
        # so the CASE flows through to ELSE.
        self.assertEqual(
            _eval_case_in_sqlite(self.case_expr, "apple_health", None),
            DEFAULT_PRIORITY,
        )

    def test_priority_ordering(self):
        # Trusted devices beat unknowns; unknowns beat the alarm clock.
        watch = _eval_case_in_sqlite(self.case_expr, "apple_health", "com.apple.health.X")
        oura = _eval_case_in_sqlite(self.case_expr, "apple_health", "com.ouraring.oura")
        unknown = _eval_case_in_sqlite(self.case_expr, "apple_health", "com.unknown.newapp")
        clock = _eval_case_in_sqlite(self.case_expr, "apple_health", "com.apple.mobiletimer")
        self.assertLess(watch, oura)
        self.assertLess(oura, unknown)
        self.assertLess(unknown, clock)


class TestSqlInjectionSafety(unittest.TestCase):
    """Patterns are hard-coded constants, but verify the escape logic works."""

    def test_single_quote_in_pattern_is_escaped(self):
        with mock.patch.object(
            source_id_priority,
            "APPLE_SOURCE_ID_PRIORITY_RULES",
            [("com.evil's.app", 42, "exact")],
        ):
            expr = source_id_priority.build_apple_priority_case("source", "source_id")
            # If escaping is broken, sqlite raises OperationalError.
            result = _eval_case_in_sqlite(expr, "apple_health", "com.evil's.app")
            self.assertEqual(result, 42)


if __name__ == "__main__":
    unittest.main(verbosity=2)
