"""The consumer raw-genotype exports this project reads, recognised by shape.

Every direct-to-consumer array vendor exports the same four facts per marker
(rsID, chromosome, position, the two alleles) and no two agree on the layout.
There is no interchange standard at this level: VCF is the field's format, and
none of these vendors ship it. The rsid TSV started as 23andMe's and the rest
cloned it with changes. Read 2026-09-23 against each vendor's help pages:

    WeGene, 23andMe        TSV, "# rsid chromosome position genotype" as a
                           COMMENT line, one two-letter genotype, "--" no call
    AncestryDNA            TSV, "rsid chromosome position allele1 allele2" as
                           a plain header line, alleles split, "0" no call
    MyHeritage, FTDNA      CSV, "RSID,CHROMOSOME,POSITION,RESULT", often
                           quoted, one two-letter result, "--" no call

Recognised by the column header rather than by a vendor's banner, which is how
this used to work: the check was one literal WeGene sentence, so a 23andMe or
AncestryDNA file of the same shape went to the text pipeline and produced
nothing, silently.

Two shapes come out, one genotype column or two allele columns, and both
become one two-character genotype with a single no-call spelling, `NO_CALL`.
Chromosome names are kept as the file prints them. Only one file is compared
with itself (the neighbour lookup), so a vendor's own numbering is consistent,
and remapping AncestryDNA's numeric sex chromosomes needs a source this module
does not have.

Pure: no file handle, no database, no clock.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass

#: The one spelling a no-call is stored under, whatever the vendor wrote.
#: A no-call is not an absence: the array tried this site and could not read
#: it, and a reader has to be told which of the two it is looking at.
NO_CALL = "--"

SHAPE_GENOTYPE = "genotype"  # one column holding both alleles
SHAPE_ALLELES = "alleles"  # allele1 and allele2 in two columns

#: How much of a file the sniff reads. 23andMe puts about twenty comment lines
#: before its column header; the old check read 100 bytes and could only ever
#: see a banner.
SNIFF_BYTES = 16 * 1024

_GENOTYPE_HEADERS = (("rsid", "chromosome", "position", "genotype"), ("rsid", "chromosome", "position", "result"))
_ALLELE_HEADER = ("rsid", "chromosome", "position", "allele1", "allele2")

#: What a no-call looks like: "--" (WeGene, 23andMe, MyHeritage) and "0"
#: (AncestryDNA, per allele), plus the empty and doubled forms of the same.
_NO_CALL_SPELLINGS = frozenset({"", "-", "--", "0", "00"})

_BUILD = re.compile(r"\b(GRCh3[78]|hg1[89]|build\s*3[678])\b", re.IGNORECASE)
_BUILD_NAMES = {"hg19": "GRCh37", "hg18": "NCBI36", "hg38": "GRCh38", "build36": "NCBI36", "build37": "GRCh37", "build38": "GRCh38"}

_VENDORS = (
    ("WeGene", "generated by wegene"),
    ("23andMe", "23andme"),
    ("AncestryDNA", "ancestrydna"),
    ("MyHeritage", "myheritage"),
    ("FamilyTreeDNA", "familytreedna"),
)


@dataclass(frozen=True)
class GenotypeFormat:
    """What the sniff found. `delimiter` is `None` for runs of whitespace."""

    shape: str
    delimiter: str | None
    vendor: str = ""
    build: str = ""


def _cells(line: str, delimiter: str | None) -> list[str]:
    parts = line.split(delimiter) if delimiter else line.split()
    return [p.strip().strip('"').strip() for p in parts]


def _delimiter(line: str) -> str | None:
    if "\t" in line:
        return "\t"
    if "," in line:
        return ","
    return None


def _header_shape(cells: list[str]) -> str | None:
    names = tuple(c.lower() for c in cells[:5] if c)
    if names[:4] in _GENOTYPE_HEADERS:
        return SHAPE_GENOTYPE
    if names[:5] == _ALLELE_HEADER:
        return SHAPE_ALLELES
    return None


def sniff(head: str | bytes | bytearray | None) -> GenotypeFormat | None:
    """The format of a raw genotype export, from the start of the file, or
    `None` when the text is not one.

    A column header is required, commented or not. A text file that merely
    contains rs-numbers is not a genotype file, and routing one into the
    genetic pipeline would swallow it without a word.
    """
    if isinstance(head, (bytes, bytearray)):
        head = bytes(head[:SNIFF_BYTES]).decode("utf-8", errors="ignore")
    text = (head or "")[:SNIFF_BYTES].lstrip("\ufeff")
    lowered = text.lower()
    vendor = next((name for name, needle in _VENDORS if needle in lowered), "")
    found = _BUILD.search(text)
    build = _BUILD_NAMES.get(re.sub(r"\s+", "", found.group(1)).lower(), found.group(1)) if found else ""
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        body = line.lstrip("#").strip()
        delimiter = _delimiter(body)
        shape = _header_shape(_cells(body, delimiter))
        if shape:
            return GenotypeFormat(shape, delimiter, vendor, build)
        if not line.startswith("#"):
            # The first real line was not a header: whatever this is, it does
            # not declare its columns.
            return None
    return None


def genotype_of(cells: list[str], shape: str) -> str:
    """The row's two alleles as one string, or `NO_CALL`."""
    if shape == SHAPE_ALLELES:
        a, b = (cells[3] if len(cells) > 3 else ""), (cells[4] if len(cells) > 4 else "")
        if a in _NO_CALL_SPELLINGS or b in _NO_CALL_SPELLINGS:
            return NO_CALL
        return (a + b).upper()
    value = cells[3] if len(cells) > 3 else ""
    if value.upper() in _NO_CALL_SPELLINGS:
        return NO_CALL
    return value.upper()


def rows(lines: Iterable[str], fmt: GenotypeFormat) -> Iterator[tuple[str, str, int, str]]:
    """`(rsid, chromosome, position, genotype)` for each data line.

    Streaming: a 33 MB export is 1.35 million lines and nothing here holds more
    than one. The header, comments, blank lines and rows whose position is not
    an integer are skipped; everything else is yielded, no-calls included,
    because a site the array could not read is still a site it tried.
    """
    need = 5 if fmt.shape == SHAPE_ALLELES else 4
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        cells = _cells(line, fmt.delimiter)
        if len(cells) < need or _header_shape(cells):
            continue
        try:
            position = int(cells[2])
        except ValueError:
            continue
        rsid, chromosome = cells[0], cells[1]
        if not rsid or not chromosome:
            continue
        yield rsid, chromosome, position, genotype_of(cells, fmt.shape)


__all__ = [
    "GenotypeFormat",
    "NO_CALL",
    "SHAPE_ALLELES",
    "SHAPE_GENOTYPE",
    "SNIFF_BYTES",
    "genotype_of",
    "rows",
    "sniff",
]
