"""
Generate Answer Middleware for Two-Stage Model Fusion.

This middleware injects a `generate_answer` tool that allows the orchestrator model
to signal when data collection is complete, triggering a switch to the responder
model for final output generation.
"""

from collections.abc import Awaitable, Callable
from typing import Any

from langchain_core.tools import tool
from langchain.agents.middleware.types import AgentMiddleware, ModelRequest, ModelResponse

import logging

logger = logging.getLogger(__name__)

# System prompt addition for two-stage protocol
GENERATE_ANSWER_PROMPT = """
## Response Generation Protocol (MANDATORY)

You are a Data Orchestrator. Your job is to gather data, then trigger response generation.

**CRITICAL: You cannot directly reply to the user!**
**To generate a response, you MUST call `generate_answer` tool.**

**Workflow:**
1. Analyze the user's question
2. Call relevant tools to collect data (can be parallel)
3. Wait for all tool results to return
4. **Call `generate_answer`** - This triggers the response generator

**RULES:**
- Do NOT write any response text to the user
- Do NOT summarize or analyze the data yourself
- Only collect data and call `generate_answer`
- The response will be generated by a specialized model

**Examples:**
User: "Hello" -> [Call generate_answer] (no tools needed)
User: "Show my data" -> [Call data tool] -> [Call generate_answer]
"""


@tool
def generate_answer() -> str:
    """
    Call this tool to generate the final response for the user.

    **You MUST call this tool to respond to the user.**
    You cannot directly write responses - this tool triggers the response generator.

    When to call:
    - After collecting all necessary data
    - When ready to answer the user's question
    - Even for simple greetings (call immediately)

    Returns:
        Triggers response generation by a specialized model
    """
    return "GENERATING_RESPONSE"


class GenerateAnswerMiddleware(AgentMiddleware):
    """
    Middleware that injects the generate_answer tool for two-stage model fusion.

    This middleware:
    1. Adds the generate_answer tool to the agent's available tools
    2. Modifies the system prompt to guide the orchestrator model on when to use this tool
    """

    def __init__(self, custom_prompt: str | None = None):
        """
        Initialize the middleware.

        Args:
            custom_prompt: Optional custom prompt to override the default GENERATE_ANSWER_PROMPT
        """
        self._custom_prompt = custom_prompt or GENERATE_ANSWER_PROMPT

    @property
    def tools(self):
        """
        Declare the tools provided by this middleware.

        Returns:
            List containing the generate_answer tool
        """
        return [generate_answer]

    def wrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], ModelResponse],
    ) -> ModelResponse:
        """
        Wrap the model call to modify the system prompt.
        """
        current_prompt = request.system_prompt or ""
        if "Response Generation Protocol" not in current_prompt:
            new_prompt = current_prompt + "\n\n" + self._custom_prompt
            request = request.override(system_prompt=new_prompt)

        return handler(request)

    async def awrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], Awaitable[ModelResponse]],
    ) -> ModelResponse:
        """
        Async version of wrap_model_call.
        """
        current_prompt = request.system_prompt or ""
        if "Response Generation Protocol" not in current_prompt:
            new_prompt = current_prompt + "\n\n" + self._custom_prompt
            request = request.override(system_prompt=new_prompt)

        return await handler(request)


__all__ = ["GenerateAnswerMiddleware", "generate_answer"]
