-- Indicator value validation rules (TH-132 W1.1)
-- Rules are evaluated at data ingestion time by ValueRangeValidator.
-- Out-of-range values are marked task_id='filtered_out_of_range', not dropped.

CREATE TABLE IF NOT EXISTS indicator_valid_rules (
    id              bigserial PRIMARY KEY,
    rule_set        varchar(64)  NOT NULL DEFAULT 'ingestion_filter',
    indicator       varchar(200) NOT NULL,
    rules           jsonb        NOT NULL,
    description     text,
    mapping_info    jsonb        DEFAULT '{}'::jsonb,
    enabled         boolean      NOT NULL DEFAULT true,
    create_time     timestamp with time zone NOT NULL DEFAULT now(),
    update_time     timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_indicator_valid_rules UNIQUE (rule_set, indicator)
);

CREATE INDEX IF NOT EXISTS idx_ivr_rule_set ON indicator_valid_rules (rule_set, enabled);

COMMENT ON TABLE  indicator_valid_rules IS 'Indicator value validation rules. Each row defines rules for one indicator under one rule_set.';
COMMENT ON COLUMN indicator_valid_rules.rule_set IS 'Rule set name: ingestion_filter (W1.1), healthy_range, diabetic_range, etc.';
COMMENT ON COLUMN indicator_valid_rules.indicator IS 'Indicator name matching StandardIndicator.name (e.g. heartRates)';
COMMENT ON COLUMN indicator_valid_rules.rules IS 'JSON array of rule expressions, e.g. [">=25", "<=350"]. All rules AND.';
COMMENT ON COLUMN indicator_valid_rules.mapping_info IS 'Indicator metadata such as unit type, e.g. {"unit": "%"}';
COMMENT ON COLUMN indicator_valid_rules.enabled IS 'Whether this rule is active. Disabled rules are skipped during validation.';

-- Seed data: ingestion_filter rules (120 indicators)
INSERT INTO indicator_valid_rules (rule_set, indicator, rules, description) VALUES
-- VITAL_SIGNS: Heart Rate
('ingestion_filter', 'heartRates',              '[">=25", "<=350"]',    'HR: <25=noise/fault, max~250'),
('ingestion_filter', 'restingHeartRates',        '[">=25", "<=220"]',    'Resting HR'),
('ingestion_filter', 'walkingHeartRates',        '[">=30", "<=250"]',    'Walking HR: at least 30'),
('ingestion_filter', 'heartRateMax',             '[">=25", "<=350"]',    'HR max'),
('ingestion_filter', 'heartRateMin',             '[">=25", "<=350"]',    'HR min'),
('ingestion_filter', 'maxHeartRateProfile',      '[">=25", "<=350"]',    'Max HR profile'),
('ingestion_filter', 'dailyAvgHeartRate',        '[">=25", "<=250"]',    'Daily avg HR'),
('ingestion_filter', 'dailyHeartRateAvg',        '[">=25", "<=250"]',    'Daily HR avg'),
('ingestion_filter', 'dailyHeartRateMax',        '[">=25", "<=350"]',    'Daily HR max'),
('ingestion_filter', 'dailyHeartRateMin',        '[">=25", "<=250"]',    'Daily HR min'),
('ingestion_filter', 'dailyRestingHeartRates',   '[">=25", "<=180"]',    'Daily resting HR'),
('ingestion_filter', 'dailyWalkingHeartRates',   '[">=30", "<=220"]',    'Daily walking HR'),
('ingestion_filter', 'dailySleepAvgHeartRate',   '[">=25", "<=200"]',    'Sleep avg HR'),
('ingestion_filter', 'dailySleepBaseHeartRate',  '[">=25", "<=200"]',    'Sleep base HR'),
('ingestion_filter', 'dailySleepLowestHeartRate','[">=25", "<=200"]',    'Sleep lowest HR'),
('ingestion_filter', 'dailySleepMaxHeartRate',   '[">=25", "<=250"]',    'Sleep max HR'),
('ingestion_filter', 'dailySleepMinHeartRate',   '[">=25", "<=200"]',    'Sleep min HR'),
-- VITAL_SIGNS: SpO2, Blood Pressure, Temperature, Respiratory
('ingestion_filter', 'oxygenSaturations',        '[">=50", "<=100"]',    'SpO2: <50%=device error, 100% valid'),
('ingestion_filter', 'systolicPressures',        '[">=40", "<=280"]',    'SBP: shock~50'),
('ingestion_filter', 'diastolicPressures',       '[">=20", "<=200"]',    'DBP: shock~20'),
('ingestion_filter', 'bodyTemperatures',         '[">=25", "<=45"]',     'Body temp: hypothermia~25, fatal~45'),
('ingestion_filter', 'skinTemperature',          '[">=15", "<=45"]',     'Skin temp: cold env~15'),
('ingestion_filter', 'wristTemperatures',        '[">=15", "<=45"]',     'Wrist temp'),
('ingestion_filter', 'temperatureDelta',         '[">=-5", "<=5"]',      'Temp delta: extreme~+/-3'),
('ingestion_filter', 'respiratoryRates',         '[">=4", "<=80"]',      'RR: deep sedation~4, neonate distress~60'),
('ingestion_filter', 'dailyRespiratoryRates',    '[">=4", "<=60"]',      'Daily RR'),
('ingestion_filter', 'dailyBaseRespiratoryRates','[">=4", "<=60"]',      'Daily base RR'),
('ingestion_filter', 'dailyMaxRespiratoryRates', '[">=4", "<=80"]',      'Daily max RR'),
('ingestion_filter', 'dailyMinRespiratoryRates', '[">=4", "<=60"]',      'Daily min RR'),
('ingestion_filter', 'dailySleepRespiratoryRate','[">=4", "<=40"]',      'Sleep RR: slower'),
('ingestion_filter', 'dailySleepSkinTemperature','[">=20", "<=42"]',     'Sleep skin temp'),
('ingestion_filter', 'dailySleepTemperatureDelta','[">=-5", "<=5"]',     'Sleep temp delta'),
('ingestion_filter', 'dailyFastRespiratoryDuration','[">=0", "<=86400000"]','ms, 1 day'),
('ingestion_filter', 'dailySlowRespiratoryDuration','[">=0", "<=86400000"]','ms, 1 day'),
('ingestion_filter', 'dailySleepFastHeartRateDuration','[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'dailySleepSlowHeartRateDuration','[">=0", "<=86400000"]','ms'),
-- BODY_COMPOSITION
('ingestion_filter', 'bodyMasss',                '[">=2", "<=300"]',     'Weight: neonate~2kg, actual max=101'),
('ingestion_filter', 'heights',                  '[">=0.3", "<=2.5"]',   'Height: infant~0.4, tallest 2.72'),
('ingestion_filter', 'bmis',                     '[">=10", "<=80"]',     'BMI: extreme emaciation~12'),
('ingestion_filter', 'bodyFatPercentages',       '[">=2", "<=70"]',      'Body fat: extreme athlete~3%'),
('ingestion_filter', 'bodyMuscle',               '[">=20", "<=70"]',     'Muscle %'),
('ingestion_filter', 'bodyWater',                '[">=30", "<=80"]',     'Body water: dehydration~40%'),
('ingestion_filter', 'bodyBone',                 '[">=1", "<=8"]',       'Bone mass: actual 2.5-4.3kg'),
('ingestion_filter', 'bodyVisFat',               '[">=1", "<=50"]',      'Visceral fat scale'),
('ingestion_filter', 'bodySubFat',               '[">=5", "<=60"]',      'Subcutaneous fat'),
('ingestion_filter', 'bodyProtein',              '[">=5", "<=30"]',      'Protein %'),
('ingestion_filter', 'basalMetabolicRate',       '[">=800", "<=4000"]',  'BMR: child~900, actual 1295-1650'),
('ingestion_filter', 'bodyFatFreeWeight',        '[">=2", "<=200"]',     'Fat-free weight'),
('ingestion_filter', 'waistCircumferences',      '[">=0.3", "<=2"]',     'Waist: child~0.4m'),
('ingestion_filter', 'dailyWeight',              '[">=2", "<=300"]',     'Daily weight'),
-- ACTIVITY (0 values valid)
('ingestion_filter', 'exerciseMinutes',          '[">=0", "<=1440"]',    '0=no exercise, 1 day'),
('ingestion_filter', 'steps',                    '[">=0", "<=100000"]',  '0=no walking, actual max=21254'),
('ingestion_filter', 'floors',                   '[">=0", "<=500"]',     'Actual max=84'),
('ingestion_filter', 'activeCalories',           '[">=0", "<=15000"]',   'Actual p99=724'),
('ingestion_filter', 'basalCalories',            '[">=0", "<=3000"]',    'Actual max=1755'),
('ingestion_filter', 'walkingRunningDistances',  '[">=0", "<=200000"]',  'Actual max=59675'),
('ingestion_filter', 'cyclingDistances',         '[">=0", "<=500000"]',  'Bike can go further'),
('ingestion_filter', 'walkingSpeeds',            '[">=0", "<=13"]',      'Actual max=8.2, sprint~12'),
('ingestion_filter', 'cyclingSpeeds',            '[">=0", "<=40"]',      'Actual 8.3'),
('ingestion_filter', 'speeds',                   '[">=0", "<=40"]',      'Same as cycling'),
('ingestion_filter', 'stepDuration',             '[">=0", "<=86400000"]','ms, 1 day'),
('ingestion_filter', 'walkingRunningDuration',   '[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'cyclingDuration',          '[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'floorsDuration',           '[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'dailySteps',               '[">=0", "<=100000"]',  'Same as steps'),
('ingestion_filter', 'dailyDistance',             '[">=0", "<=200000"]',  'Same as distance'),
('ingestion_filter', 'dailyFloors',              '[">=0", "<=500"]',     'Same as floors'),
('ingestion_filter', 'dailyCaloriesActive',      '[">=0", "<=15000"]',   'Same'),
('ingestion_filter', 'dailyCaloriesBasal',       '[">=0", "<=3000"]',    'Same'),
('ingestion_filter', 'dailyTotalCalories',       '[">=0", "<=20000"]',   'Active+basal'),
('ingestion_filter', 'sedentaryTime',            '[">=0", "<=1440"]',    '1 day'),
('ingestion_filter', 'restingTime',              '[">=0", "<=1440"]',    '1 day'),
('ingestion_filter', 'dailyActivityIntensityHigh','[">=0", "<=1440"]',   '1 day'),
('ingestion_filter', 'dailyActivityIntensityMedium','[">=0", "<=1440"]', '1 day'),
('ingestion_filter', 'dailyActivityIntensityLow','[">=0", "<=1440"]',    '1 day'),
-- METABOLIC
('ingestion_filter', 'bloodGlucoses',            '[">=20", "<=600"]',    'CGM min 20, DKA~500, actual max=504'),
('ingestion_filter', 'hrvDatas',                 '[">=5", "<=500"]',     'Extreme low~5ms, actual p1=13'),
('ingestion_filter', 'hrvRMSSD',                 '[">=5", "<=500"]',     'Same as HRV'),
('ingestion_filter', 'hrvMax',                   '[">=5", "<=500"]',     'HRV max'),
('ingestion_filter', 'hrvMin',                   '[">=0", "<=500"]',     'HRV min: can be very low'),
('ingestion_filter', 'bodyCholesterol',          '[">=1", "<=20"]',      'Total cholesterol'),
('ingestion_filter', 'bodyCholesterolHDL',       '[">=0.3", "<=8"]',     'HDL'),
('ingestion_filter', 'bodyCholesterolLDL',       '[">=0.3", "<=15"]',    'LDL'),
('ingestion_filter', 'bodyCholesterolTriglycerides','[">=0.2", "<=20"]', 'TG'),
('ingestion_filter', 'dailySleepAvgHrv',         '[">=5", "<=500"]',     'Sleep HRV'),
('ingestion_filter', 'dailyWorkoutAvgHrv',       '[">=5", "<=500"]',     'Workout HRV'),
-- SLEEP (ms durations: 0 valid)
('ingestion_filter', 'sleepAnalysis_Awake',      '[">=0", "<=86400000"]','ms, 0=valid'),
('ingestion_filter', 'sleepAnalysis_Asleep(Deep)','[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'sleepAnalysis_Asleep(Core)','[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'sleepAnalysis_Asleep(REM)','[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'sleepAnalysis_Asleep(Total)','[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'sleepAnalysis_Asleep(Unspecified)','[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'sleepAnalysis_InBed',      '[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'napDuration',              '[">=0", "<=86400000"]','ms'),
('ingestion_filter', 'sleepDuration',            '[">=0", "<=24"]',      'hours'),
('ingestion_filter', 'totalSleepTime',           '[">=0", "<=86400"]',   'seconds'),
('ingestion_filter', 'sleepLatency',             '[">=0", "<=43200"]',   'seconds, max half day'),
('ingestion_filter', 'sleepEfficiency',          '[">=5", "<=100"]',     '<5%=device error'),
('ingestion_filter', 'sleepConsistency',         '[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'sleepQuality',             '[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'sleepPerformance',         '[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'sleepOverallScore',        '[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'sleepDisturbances',        '[">=0", "<=200"]',     '0=no disturbance'),
('ingestion_filter', 'dailySleepEfficiency',     '[">=5", "<=100"]',     'Same as sleepEfficiency'),
('ingestion_filter', 'dailyDeepSleepPercentage', '[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'dailyLightSleepPercentage','[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'dailyRemSleepPercentage',  '[">=0", "<=100"]',     '0% possible'),
('ingestion_filter', 'dailyAwakeDurationPercentage','[">=0", "<=100"]',  '0% possible'),
('ingestion_filter', 'dailySleepContinuity',     '[">=0", "<=1"]',       'ratio'),
('ingestion_filter', 'dailySleepSffcy',          '[">=0", "<=1"]',       'ratio'),
('ingestion_filter', 'dailyAwakeTimes',          '[">=0", "<=200"]',     'Same as disturbances'),
('ingestion_filter', 'dailySleepCycleTimes',     '[">=0", "<=30"]',      'Max ~8 per night'),
-- PERFORMANCE
('ingestion_filter', 'stressLevel',              '[">=0", "<=100"]',     '0=no stress'),
('ingestion_filter', 'recoveryScore',            '[">=0", "<=100"]',     'Percentage'),
('ingestion_filter', 'workoutDuration',          '[">=0", "<=1440"]',    '1 day'),
('ingestion_filter', 'workoutDurationHigh',      '[">=0", "<=1440"]',    '0=none'),
('ingestion_filter', 'workoutDurationLow',       '[">=0", "<=1440"]',    '0=none'),
('ingestion_filter', 'workoutDurationMedium',    '[">=0", "<=1440"]',    '0=none'),
('ingestion_filter', 'altitudeGain',             '[">=0", "<=15000"]',   'Everest 8849m'),
('ingestion_filter', 'altitudeChange',           '[">=-15000", "<=15000"]','Can be negative')
ON CONFLICT (rule_set, indicator) DO NOTHING;
