"""Regenerate ``mirobody/indicator/zh_fold.py`` — the zh-Hant → zh-Hans table.

    ./.venv/bin/python scripts/gen_zh_fold.py

Needs ``zhconv``, which is a BUILD dependency (the ``indicator-build`` extra),
not a runtime one. That is the whole point of generating a table: the engine's
install floor stays "the wheel plus numpy", and a 20 KB pair of strings does at
runtime what a dependency would.

Scope is single-codepoint mappings inside CJK Unified Ideographs
(U+4E00–U+9FFF) whose target is also in that block. Multi-character phrase
conversion is deliberately NOT included — that is where zhconv's ambiguity
handling lives (``乾/幹`` → ``干`` depends on context), and a resolver must not
guess. Terminology that genuinely differs between regions is curated in
``res/resolver_overrides.tsv`` instead, where a human writes down the intent.
"""

from __future__ import annotations

import pathlib
import sys

HEADER = '''"""zh-Hant → zh-Hans character folding, so a Traditional query finds a
Simplified alias.

GENERATED by ``scripts/gen_zh_fold.py`` — do not edit by hand.

**Why the engine needs this at all.** The alias lexicon build already mirrors
every Simplified key to its Traditional form
(``fhir/embeddings/lexicon._expand_zh_traditional``), so the shipped bundle
carries 3,161 Traditional keys. But ``res/resolver_overrides.tsv`` is a RUNTIME
file and gets no such expansion, and it is where the hand-curated everyday
panel terms live. The result was a split that looked arbitrary from outside:

    血紅蛋白    -> 718-7    (reached the bundle via the build's expansion)
    白細胞      -> nothing  (its Simplified form is an override row)

Folding the QUERY is the symmetric half of what the build does to the CORPUS,
and it covers overrides, curated files and raw user input in one place.

**What this does NOT do.** Folding is a script transform, not a translation.
Taiwan clinical vocabulary differs from mainland vocabulary in WORD CHOICE, and
folding those is actively dangerous: ``血紅素`` folds to ``血红素``, which the
index answers with 4548-4 — HbA1c — while in Taiwan 血紅素 *is* haemoglobin.
That is the ``血红蛋白 -> HbA1c`` failure with a new hat on. Region-specific
terms are curated in ``resolver_overrides.tsv`` under their Traditional
spelling, and ``_candidate_keys`` tries the term as written before any variant,
so a curated row always beats a fold.
"""

from __future__ import annotations

__all__ = ["fold_to_hans"]

'''

FOOTER = '''

#: Built once at import: ~3.3k entries, and the fold is then one C-level call.
_TABLE = str.maketrans(_HANT, _HANS)


def fold_to_hans(text: str) -> str:
    """Traditional → Simplified, character by character.

    Returns `text` unchanged when it contains nothing to fold, so a caller can
    cheaply skip a duplicate lookup by comparing identity of content.
    """
    return text.translate(_TABLE) if text else text
'''


def main() -> int:
    try:
        import zhconv
    except ImportError:
        print(
            "zhconv is required to regenerate this table:\n"
            "  VIRTUAL_ENV=$PWD/.venv uv pip install zhconv",
            file=sys.stderr,
        )
        return 1

    pairs: list[tuple[str, str]] = []
    for cp in range(0x4E00, 0xA000):
        ch = chr(cp)
        hans = zhconv.convert(ch, "zh-hans")
        if len(hans) == 1 and hans != ch and 0x4E00 <= ord(hans) < 0xA000:
            pairs.append((ch, hans))

    hant = "".join(a for a, _ in pairs)
    hans = "".join(b for _, b in pairs)

    out = pathlib.Path(__file__).resolve().parent.parent / "mirobody" / "indicator" / "zh_fold.py"
    out.write_text(
        HEADER
        + f"#: {len(pairs):,} single-codepoint mappings, as two parallel strings.\n"
        + f"_HANT = {hant!r}\n\n_HANS = {hans!r}\n"
        + FOOTER,
        encoding="utf-8",
    )
    print(f"wrote {out} — {len(pairs):,} mappings, {out.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
